services:
  - type: web
    name: shipment-management-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CORS_ORIGIN
        sync: false
      - key: UPLOAD_DIR
        value: /opt/render/project/src/server/uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: ALLOWED_FILE_TYPES
        value: image/jpeg,image/png,image/gif,application/pdf
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1

